version: "3"
services:
  jupyter:
    build:
      context: .
    environment:
      - JUPYTER_ENABLE_LAB='true'
    command: start-notebook.sh --ImmerseConfig.immerse_dir=/home/jovyan/immerse/dist --NotebookApp.notebook_dir=/home/jovyan --NotebookApp.token=''
    network_mode: host
    ports:
      - "8888:8888"
  omnisci:
    image: mapd/mapd-ce-cpu
    network_mode: host
    ports:
      - "9092:9092"
