channels:
  - conda-forge
  - defaults
dependencies:
  - arrow-cpp=0.12.1
  - blosc=1.16.3
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - certifi=2019.3.9
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - geos=3.7.1
  - geotiff=1.4.3
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.1.7
  - glib=2.58.3
  - glog=0.3.5
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - jpeg=9c
  - json-c=0.13.1
  - kealib=1.4.10
  - libarchive=3.3.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libdap4=3.19.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.36
  - libprotobuf=3.6.1
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - lz4-c=1.8.1.2
  - lzo=2.10
  - nodejs=11.11.0
  - numpy=1.16.2
  - openblas=0.3.5
  - openjdk=8.0.192
  - openjpeg=2.3.0
  - openssl=1.1.1b
  - pcre=8.41
  - pixman=0.34.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - pthread-stubs=0.4
  - thrift-cpp=0.12.0
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - zstd=1.3.3
  - curl=7.64.0
  - krb5=1.16.1
  - libcurl=7.64.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpq=11.2
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - pip=19.0.3
  - postgresql=11.2
  - python=3.7.3
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.27.2
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - altair==2.4.1
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - decorator==4.4.0
    - defusedxml==0.5.0
    - entrypoints==0.3
    - ibis-framework==1.0.0
    - ipdb==0.12
    - ipykernel==5.1.0
    - ipython==7.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10
    - jsonschema==3.0.1
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - jupyterlab==1.0.0a3
    - jupyterlab-server==0.3.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - multipledispatch==0.6.0
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.8
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.3.4
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pyarrow==0.12.1
    - pygments==2.3.1
    - pymapd==0.10.0
    - pyrsistent==0.14.11
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pyyaml==5.1
    - pyzmq==18.0.1
    - regex==2019.3.12
    - send2trash==1.5.0
    - six==1.12.0
    - sqlalchemy==1.3.2
    - terminado==0.8.2
    - testpath==0.4.2
    - thrift==0.11.0
    - toolz==0.9.0
    - tornado==6.0.2
    - traitlets==4.3.2
    - vdom==0.6
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
